controller_manager:
  ros__parameters:
    robot_description_topic: /robot_description
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    # diff_drive_controller:
    #   type: diff_drive_controller/DiffDriveController

    effort_controller:
      type: effort_controllers/JointGroupEffortController

    wheeled_bipedal_controller:
      type: wheeled_bipedal_controller/WheeledBipedalController

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: "imu_sensor"
    frame_id: "imu_link"

effort_controller:
  ros__parameters:
    joints:
      - RR_hip_joint
      - LR_hip_joint
      - RF_hip_joint
      - LF_hip_joint
      - left_wheel_joint
      - right_wheel_joint

wheeled_bipedal_controller:
  ros__parameters:
    # 左前电机, 左后电机, 右前电机, 右后电机, 左轮, 右轮
    joints:
      [
        "LF_hip_joint",
        "LR_hip_joint",
        "RF_hip_joint",
        "RR_hip_joint",
        "left_wheel_joint",
        "right_wheel_joint",
      ]
    joints_bias_values: [1.6407, 1.6007, 1.6707, 1.5707] # upper_link关节电机state position和tf的偏差值 bias = tf - state
    command_interface_type: "effort" # "position", "velocity", "effort"
    joint_command_limit: 5.0
    imu_name: "imu_sensor"
    pitch_compensation: 2.0
    rod_lengths: [0.150, 0.250, 0.250, 0.150, 0.107992374] # L1 - L5
    wheel_radius: 0.069
    wheel_separation: 0.445
    wheel_mass: 2.1
    leg_length_min: 0.20
    leg_length_max: 0.37
    # LQR的K矩阵拟合多项式的系数（从低次项系数到高次项系数排序）
    K11poly: [1.3248, -70.5012, 136.0298, -103.5741]
    K12poly: [0.2314, -4.7932, 0.8240, 1.9439]
    K13poly: [0.0095, -0.1518, 0.3581, -0.3086]
    K14poly: [0.3147, -5.0322, 11.8502, -10.2086]
    K15poly: [0.6384, -2.2793, 2.4289, -0.4425]
    K16poly: [0.3913, -0.3554, -1.4302, 2.3812]
    K21poly: [4.8793, 46.0317, -192.2447, 207.7976]
    K22poly: [-0.0811, 7.7601, -21.2803, 19.1016]
    K23poly: [0.0373, -0.0456, -0.0919, 0.1826]
    K24poly: [1.2345, -1.5029, -3.0569, 6.0537]
    K25poly: [-0.3564, 10.9718, -27.7924, 25.0648]
    K26poly: [-0.4379, 6.2418, -14.4020, 12.1905]

    # K11poly: [0.0]
    # K12poly: [0.0]
    # K13poly: [0.0]
    # K14poly: [0.0]
    # K15poly: [0.0]
    # K16poly: [0.0]
    # K21poly: [0.0]
    # K22poly: [0.0]
    # K23poly: [0.0]
    # K24poly: [0.0]
    # K25poly: [0.0]
    # K26poly: [0.0]

    debug: true # 是否在每次update时获取动态参数

    # PID 参数
    # 左腿
    # left:
    #   leg_length_P: 0.0
    #   leg_length_I: 0.0
    #   leg_length_D: 0.0
    #   leg_length: 0.25 # 初始腿长
    # # 右腿
    # right:
    #   same_with_left: false # true表示与左腿采用相同参数
    #   leg_length_P: 0.0
    #   leg_length_I: 0.0
    #   leg_length_D: 0.0
    #   leg_length: 0.25 # 初始腿长
    # 左腿
    left:
      leg_length_P: 600.0
      leg_length_I: 30.0
      leg_length_D: 1.0
      leg_length: 0.25 # 初始腿长
    # 右腿
    right:
      same_with_left: false # true表示与左腿采用相同参数
      leg_length_P: 600.0
      leg_length_I: 50.0
      leg_length_D: 1.0
      leg_length: 0.25 # 初始腿长
    # 腿长PID前馈值
    leg_length_feedforward: 0.0
    # 左右两腿 phi0 角度差pid控制器
    delta_phi0_P: 40.0
    delta_phi0_I: 20.0
    delta_phi0_D: 0.075
    # 角速度PID
    angular_vel_P: 0.0
    angular_vel_I: 0.0
    angular_vel_D: 0.0

    roll_error_P: 0.0
    roll_error_I: 0.0
    roll_error_D: 0.0

# diff_drive_controller:
#   ros__parameters:
#     left_wheel_names: ["left_wheel_joint"]
#     right_wheel_names: ["right_wheel_joint"]

#     wheel_radius: 0.069
#     wheel_separation: 0.445

#     odom_frame_id: "odom"
#     base_frame_id: "base_footprint"

#     pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
#     twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

#     enable_odom_tf: true
#     publish_frequency: 50.0

#     linear.x.has_velocity_limits: true

#     linear.x.max_velocity: 1.0
#     linear.x.min_velocity: -1.0

#     angular.z.max_velocity: 1.0
#     angular.z.min_velocity: -1.0
