controller_manager:
  ros__parameters:
    robot_description_topic: /robot_description
    update_rate: 500

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    imu_sensor_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    # diff_drive_controller:
    #   type: diff_drive_controller/DiffDriveController

    # effort_controller:
    #   type: effort_controllers/JointGroupEffortController

    wheeled_bipedal_controller:
      type: wheeled_bipedal_controller/WheeledBipedalController

gazebo_ros2_control:
  ros__parameters:
    # 必须为每一个使用 position 或 velocity 接口的关节提供 PID
    pid_gains:
      position:
        LF_hip_joint:
          kp: 10.0
          ki: 0.1
          kd: 1.0
        LR_hip_joint:
          kp: 10.0
          ki: 0.1
          kd: 1.0
        RF_hip_joint:
          kp: 10.0
          ki: 0.1
          kd: 1.0
        RR_hip_joint:
          kp: 10.0
          ki: 0.1
          kd: 1.0

imu_sensor_broadcaster:
  ros__parameters:
    sensor_name: "imu_sensor"
    frame_id: "imu_link"

effort_controller:
  ros__parameters:
    joints:
      - LF_hip_joint
      - LR_hip_joint
      - RF_hip_joint
      - RR_hip_joint
      - left_wheel_joint
      - right_wheel_joint

wheeled_bipedal_controller:
  ros__parameters:
    # 左前电机, 左后电机, 右前电机, 右后电机, 左轮, 右轮
    joints:
      [
        "LF_hip_joint",
        "LR_hip_joint",
        "RF_hip_joint",
        "RR_hip_joint",
        "left_wheel_joint",
        "right_wheel_joint",
      ]
    joints_bias_values: [0.4314, 2.6247, 0.4043, 2.6011] # upper_link关节电机state position和tf的偏差值 bias = tf - state
    command_interface_type: "effort" # "position", "velocity", "effort"
    imu_name: "imu_sensor"
    rod_lengths: [0.150, 0.250, 0.250, 0.150, 0.107992374] # L1 - L5
    wheel_radius: 0.069
    wheel_separation: 0.445
    wheel_mass: 0.85254
    leg_length_min: 0.15
    leg_length_max: 0.37
    # LQR的K矩阵拟合多项式的系数（从低次项系数到高次项系数排序）
    K11poly: [-2.4003, -74.4638, 141.7223, -144.3006]
    K12poly: [-0.3530, -5.8864, -0.3597, -6.9189]
    K13poly: [0.0152, -1.5131, 4.3497, -4.2655]
    K14poly: [-0.5207, -35.8905, 109.2646, -110.7116]
    K15poly: [21.6983, -123.6705, 255.5451, -184.0317]
    K16poly: [1.2826, -4.9968, 5.5036, -0.6879]
    K21poly: [16.0819, -82.4169, 164.4675, -111.5919]
    K22poly: [2.0054, -9.7618, 21.3189, -15.3129]
    K23poly: [0.3385, -1.7607, 3.5503, -2.5014]
    K24poly: [11.3833, -67.4853, 155.8719, -128.4311]
    K25poly: [5.5447, 135.1007, -390.7470, 383.7428]
    K26poly: [0.5967, 5.1297, -14.2911, 13.5050]

    debug: true # 是否在每次update时获取动态参数

    # PID 参数
    # 左腿
    left:
      leg_length_P: 1000.0
      leg_length_I: 0.0
      leg_length_D: 125.0
      leg_length: 0.20 # 初始腿长
    # 右腿
    right:
      same_with_left: true # true表示与左腿采用相同参数
      leg_length_P: 1250.0
      leg_length_I: 1000.0
      leg_length_D: 125.0
      leg_length: 0.20 # 初始腿长
    # 左右两腿 phi0 角度差pid控制器
    delta_phi0_P: 500.0
    delta_phi0_I: 100.0
    delta_phi0_D: 4.0
    # 角速度PID
    angular_vel_P: 2.0
    angular_vel_I: 7.0
    angular_vel_D: 0.0001

    roll_error_P: 0.0
    roll_error_I: 10.0
    roll_error_D: 0.0001

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]

    wheel_radius: 0.069
    wheel_separation: 0.445

    odom_frame_id: "odom"
    base_frame_id: "base_footprint"

    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    enable_odom_tf: true
    publish_frequency: 50.0

    linear.x.has_velocity_limits: true

    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0

    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
